services:
  ermc-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - RAM=6144
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 6G
    restart: always
