
CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY,
	email TEXT UNIQUE,
	passwordHash TEXT,
	isGuest BOOLEAN NOT NULL DEFAULT FALSE,
	notifyToken TEXT,
	cloudFolder TEXT,
	cloudTokenEnc TEXT
);

CREATE TABLE IF NOT EXISTS roles (
	id INTEGER PRIMARY KEY,
	name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS user_roles (
	userId INTEGER NOT NULL,
	roleId INTEGER NOT NULL,

	PRIMARY KEY (userId, roleId),

	FOREIGN KEY (userId)
		REFERENCES users(id)
		ON UPDATE CASCADE
		ON DELETE CASCADE,

	FOREIGN KEY (roleId)
		REFERENCES roles(id)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS sessions (
	id INTEGER PRIMARY KEY,
	userId INTEGER NOT NULL,
	refreshHash TEXT NOT NULL,
	deviceId TEXT NOT NULL,

	UNIQUE (userId, deviceId)

	FOREIGN KEY (userId)
		REFERENCES users(id)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);
